import { THANK_YOU_POPUP_HEIGHT, THANK_YOU_POPUP_WIDTH } from './ThankYou.style';

export const CHOOSE_PROGRAM_POPUP_HEIGHT = THANK_YOU_POPUP_HEIGHT;
export const CHOOSE_PROGRAM_POPUP_WIDTH = THANK_YOU_POPUP_WIDTH;

