# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
READONLY = ENV['READONLY'] == 'true'

platform :ios do
  desc "Download and install certificates and provisioning profiles"
  lane :bootstrap do
    match(type: "development", app_identifier: "com.nuli.app.wip", git_branch: "nuli", force_for_new_devices: true, readonly: READONLY)
    match(type: "development", app_identifier: "com.nuli.app.wip.OneSignalNotificationServiceExtension", git_branch: "nuli", force_for_new_devices: true, readonly: READONLY)

    match(type: "adhoc", app_identifier: "com.nuli.app.staging", git_branch: "nuli", force_for_new_devices: true, readonly: READONLY)
    match(type: "adhoc", app_identifier: "com.nuli.app.staging.OneSignalNotificationServiceExtension", git_branch: "nuli", force_for_new_devices: true, readonly: READONLY)

    match(type: "appstore", app_identifier: "com.nuli.app", git_branch: "nuli", force_for_new_devices: true, readonly: READONLY)
    match(type: "appstore", app_identifier: "com.nuli.app.OneSignalNotificationServiceExtension", git_branch: "nuli", force_for_new_devices: true, readonly: READONLY)

    match(type: "adhoc", app_identifier: "com.nuli.app", git_branch: "nuli", force_for_new_devices: true, readonly: READONLY) # Testing only
    match(type: "adhoc", app_identifier: "com.nuli.app.OneSignalNotificationServiceExtension", git_branch: "nuli", force_for_new_devices: true, readonly: READONLY) # Testing only
  end
end
